### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by ofirkris** [Tengfei-Wang/external-internal-inpainting#2]
Hi,

Thanks for the GitHub repo. Can I check if the pre-trained weights will be released anywhere?

**Comment by Tengfei-Wang** [comment]
> Hi,
> 
> Thanks for the GitHub repo. Can I check if the pre-trained weights will be released anywhere?

Hi,
Our colorization is based on internal learning, which means different weights are applied to different images. You can easily try our code on your images, and it takes ~30s for each image.
