### ISSUE TITLE
Is it possible to use for higher resolution images? 

### ISSUE THREAD

**Issue by roimulia2** [Tengfei-Wang/external-internal-inpainting#3]
Great paper! Loved it.

For real user-case scenarios, is it possible to use it for HQ images (Full HD, for example)? 

Thanks!

**Comment by Tengfei-Wang** [comment]
Hi,
I expect the method can be applied to high-resolution images, although the largest image size used in our paper is 512x640 (Places2). There are two stages in our pipeline. For the first stage, I recommend trying some high-resolution inpainting networks as the backbone network for HQ images. For the second colorization stage, the network is designed for arbitrary image sizes, but you may need more iterations to convergence for HQ images.

**Comment by roimulia2** [comment]
Hey, thank for you replying! 

Is the pipe-line is sealed? I mean, is it part of the entire model, or it's two external methods (in this case, I can easily change the backbone model, i.e replace Places2, is that correct)?

**Comment by Tengfei-Wang** [comment]
> Hey, thank for you replying!
> 
> Is the pipe-line is sealed? I mean, is it part of the entire model, or it's two external methods (in this case, I can easily change the backbone model, i.e replace Places2, is that correct)?

Hi,
The internal colorization is independent to the inpainting backbone models.  You can train an inpainting model from scratch or just use some well-trained inpainting models to obtain some grayscale results. These results can then be colorized with our code.
