### ISSUE TITLE
Red artifact

### ISSUE THREAD

**Issue by huoxiangzuo** [Tengfei-Wang/external-internal-inpainting#5]
Hey, nice work! 

In your project website examples, is it possible that the resulting red artifacts are caused by the red mask?

**Comment by Tengfei-Wang** [comment]
Hi,
The red mask is only used to visualize the masked regions in the examples, instead of actual inputs of networks. In our experiment, all input masks are binary masks (black-and-white), and thus all masked pixels are set to 0 (black).
